---
# handlers file for kubernetes-master
- name: start ntp
  service: name=ntpd enabled=yes state=started

- name: restart ntp
  service: name=ntpd state=restarted

- name: enable kube-apiserver
  systemd: name=kube-apiserver enabled=yes

- name: restart kube-apiserver
  systemd: name=kube-apiserver state=restarted

- name: enable kube-controller-manager
  systemd: name=kube-controller-manager enabled=yes

- name: restart kube-controller-manager
  systemd: name=kube-controller-manager state=restarted

- name: enable kube-scheduler
  systemd: name=kube-scheduler enabled=yes

- name: restart kube-scheduler
  systemd: name=kube-scheduler state=restarted
