---
# handlers file for kubernetes-master
- name: start ntp
  service: name=ntpd enabled=true state=started use=service

- name: restart ntp
  service: name=ntpd state=restarted use=service

- name: start kubelet
  service: name=kubelet enabled=true state=started use=service

- name: restart kubelet
  service: name=kubelet state=restarted use=service

- name: start docker
  service: name=docker enabled=true state=started use=service

- name: restart docker
  service: name=kube-controller-manager state=restarted use=service

